name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Wait for the "test" job to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove the existing container (if it exists)
            docker stop trade-order-service || true
            docker rm trade-order-service || true

            # Pull the latest code from GitHub
            cd /home/ubuntu/blockhuse-test
            git pull origin main

            # Build the Docker image
            docker build -t trade-order-service .

            # Run the updated container
            docker run -d -p 80:80 --name trade-order-service trade-order-service